webapp/urls.py
from django.urls import path
from django.shortcuts import redirect
from . import views
from django.contrib.auth import views as auth_views

app_name = 'webapp'
urlpatterns = [
    path('home/', views.home, name='home'),
    path('signup/', views.signup, name='signup'),
    path('login/', auth_views.LoginView.as_view(template_name='webapp/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='webapp/logout.html'), name='logout'),
    path('change-password/', views.change_password, name='change-password'),
    # Reset password
    path('password-reset/',
         auth_views.PasswordResetView.as_view(template_name='webapp/password_reset.html', success_url='password_reset_done'),
         name='password_reset'),
    path('password-reset/password_reset_done',
         auth_views.PasswordResetDoneView.as_view(template_name='webapp/password_reset_done.html'),
         name='password_reset_done'),
    path('password-reset-confirm/<uidb64>/<token>/',
         auth_views.PasswordResetConfirmView.as_view(template_name='webapp/password_reset_confirm.html'),
         name='password_reset_confirm'),
    path('password-reset-complete/',
         auth_views.PasswordResetCompleteView.as_view(template_name='webapp/password_reset_complete.html'),
         name='password_reset_complete'),
]

zalego/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('webapp.urls'))
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

webapp/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from django.conf import settings
from PIL import Image

from django.contrib.auth.models import User
from django.db.models.signals import post_save
from django.dispatch import receiver

class ZalegoDet(models.Model):
    user = models.OneToOneField(User,on_delete=models.CASCADE)
    gender = models.CharField(max_length=30)
    lang = models.CharField(max_length=30)
    image = models.ImageField(default='avatar.jpg', upload_to='profile_pics')

    def __str__(self):
        return f'{self.user.username} Profile '
    # override save method to create profile on save method call
    @receiver(post_save, sender=User)
    def additional_fields(sender, instance, created, **kwargs):
        if created:
            ZalegoDet.objects.create(user=instance)
        instance.zalegodet.save()

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)
        img = Image.open(self.image.path)
        if img.height > 300 or img.width >300:
            output_size = (300, 300)
            img.thumbnail(output_size)
            img.save(self.image.path) # save it back to the path

webapp/forms.py
from django import forms
from django.contrib.auth.models import User
from django.contrib.auth.forms import UserCreationForm
from django.core.exceptions import ValidationError
from django.forms import ModelForm
from .models import ZalegoDet
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User


class SignUpForm(UserCreationForm):
    GENDER_CHOICES = (
        ('male', "male"),
        ('female', 'female'),

    )
    LANGUAGE_CHOICES =(
        ('java', 'java'),
        ('c','c'),
        ('python','python'),
    )
    email = forms.EmailField()
    gender = forms.ChoiceField(choices=GENDER_CHOICES, required=True)
    lang = forms.ChoiceField(choices=LANGUAGE_CHOICES, required=True)
    image = forms.ImageField(required=False)


    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'email','gender', 'image','lang', 'username','password1', 'password2',)

webapp/views.py
from django.contrib.auth import login, authenticate
from django.shortcuts import render, redirect,HttpResponse
from .forms import SignUpForm
from django.contrib.auth.forms import UserCreationForm,\
    UserChangeForm, PasswordChangeForm
from django.contrib.auth import update_session_auth_hash
from django.contrib.auth.decorators import login_required
from django.contrib import messages


def signup(request):
    if request.method == 'POST':
        form = SignUpForm(request.POST)
        if form.is_valid():
            user = form.save()
            user.refresh_from_db()  # load the profile instance created by the signal
            user.zalegodet.gender = form.cleaned_data.get('gender')
            user.zalegodet.lang = form.cleaned_data.get('lang')
            user.save()
            messages.success(request, 'Account created')
            return redirect('webapp:login')
            # raw_password = form.cleaned_data.get('password1')
            # user = authenticate(username=user.username, password=raw_password)
            # login(request, user)
            # return redirect('home')
    else:
        form = SignUpForm()
    return render(request, 'webapp/form.html', {'form': form})
@login_required
def home(request):
    return render(request,'webapp/profile.html')

def change_password(request):
    if request.method == 'POST':
        form = PasswordChangeForm(data=request.POST,user=request.user)

        if form.is_valid():
            form.save()
            update_session_auth_hash(request, form.user)
            return redirect('profile')
        else:
            return redirect('/account /')
    else:
        form = PasswordChangeForm(user=request.user)
        args = {'form': form}
        return render(request, 'webapp/change_password.html', args)

webapp/templates/base.html
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">
<head>
    <meta charset="UTF-8">
    <title>FORM</title>
    {% load staticfiles %}
    <link rel="stylesheet" href="{% static 'webapp/css/custom.css' %}" type="text/css"/>
    <link rel="stylesheet" href="{% static 'webapp/css/bootstrap.min.css' %}" type="text/css"/>


</head>
<div class="col-md-8 offset-2">
{% if messages %}
    {% for message in messages %}
        <div class="alert alert-{{ message.tags }} alert-dismissible" role="alert">
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
            {{ message }}
        </div>
    {% endfor %}
{% endif %}
</div>
<body style="background-color: aliceblue">
		<div class="container">
	               		<a href="{% url 'webapp:signup' %}"><h1 class="display-4" style="color: #ba8b00">ZALEGO</h1></a>
	               	</div>
                    {% if user.is_authenticated %}
                       <div class="navbar-nav text-right mr-5"><a href="{% url 'webapp:change-password' %}" style="color: blue">(change password)</a>
                       <a href="{% url 'webapp:logout' %}" style="color: blue">(logout)</a>
	               	    </div>
                    {% else %}
                        <div class="navbar-nav text-right mr-5"><a href="{% url 'webapp:login' %}" style="color: blue">(login)</a>
	               	    </div>
                    {% endif %}

<div class="container">
{% block content %}

{% endblock %}
</div>
</body>
</html>

webapp/templates/webapp/change_password.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-8 offset-2">
        <h2 class="text-center pt-5">Change password Form</h2>
        <hr>

        <form method="post" class="border border-dark rounded p-3 bg-dark text-white">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <div class="control-label col-sm-7">
                    <button type="submit" class="btn btn-primary">Change password</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

webapp/templates/webapp/form.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-8 offset-2">
        <h2 class="text-center pt-5">Registration Form</h2>
        <hr>

        <form method="post" class="border border-dark rounded p-3 bg-dark text-white">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <div class="control-label col-sm-7">
                    <button type="submit" class="btn btn-primary">REGISTER</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

webapp/templates/webapp/login.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-8 offset-2">
        <h2 class="text-center pt-5">Login Form</h2>
        <hr>

        <form method="post" class="border border-dark rounded p-3 bg-dark text-white">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <div class="control-label col-sm-7">
                    <button type="submit" class="btn btn-primary">Login</button>
                </div>
            </div>
        </form>
    <a href="{% url 'webapp:password_reset' %}">Forgot password</a> <br>
                    <a href="{% url 'webapp:signup' %}"> Not Registered </a>
    </div>
{% endblock %}

webapp/templates/webapp/logout.html
{%  extends 'base.html' %}
{% block content %}
<h4>Zalego</h4>
you logged out successfully
{% endblock %}

webapp/templates/webapp/password_reset.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-8 offset-2">
        <h2 class="text-center pt-5">Reset Password Form</h2>
        <hr>

        <form method="post" class="border border-dark rounded p-3 bg-dark text-white">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <div class="control-label col-sm-7">
                    <button type="submit" class="btn btn-primary">Request Password Reset</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

webapp/templates/webapp/password_reset_complete.html
{% extends 'base.html' %}

{% block content %}

  <div class="alert alert-info">Your password has been set </div>
    <a href="{% url 'login' %}">Sign In Here</a>

{% endblock %}

webapp/templates/webapp/password_reset_confirm.html
{% extends 'base.html' %}
{% load crispy_forms_tags %}
{% block content %}
    <div class="col-md-8 offset-2">
        <h2 class="text-center pt-5">Set New Password Form</h2>
        <hr>

        <form method="post" class="border border-dark rounded p-3 bg-dark text-white">
            {% csrf_token %}
            {{ form|crispy }}
            <div class="form-group">
                <div class="control-label col-sm-7">
                    <button type="submit" class="btn btn-primary">Reset Password</button>
                </div>
            </div>
        </form>
    </div>
{% endblock %}

webapp/templates/webapp/password_reset_done.html
{% extends 'base.html' %}

{% block content %}

  <div class="alert alert-info">An email has been sent to reset your password</div>

{% endblock %}

webapp/templates/webapp/profile.html
{% extends 'base.html' %}
{% load static %}
{% block content %}
    <div class="offset-3 col-6">
            <div class="container">
                <div class="card w-75 mt-5 btn-info">
                    <div class="card-body">
            <img src="{% if user.zalegodet.image %}{{ user.zalegodet.image.url }} {% else %}{% static 'webapp/img/avatar.jpg' %} {% endif %}" width="140" height="140" class="rounded-circle">
            <p><strong>Gender: {{ user.first_name }} {{ user.last_name }}</strong> <br></p>
            <p><strong>Gender: {{ user.zalegodet.gender }}</strong> <br></p>
            <p><strong>Language: {{ user.zalegodet.lang }}</strong> <br></p>
            <p><strong>Username: {{ user.username }}</strong></p>

        </div>

    </div>
            </div>
    </div>


{% endblock %}